#%RAML 1.0 Library
types:

  ArticlesResponse200:
    properties:
      id: string
      title: string
      content: string
      createdAt: number
    example: !include ami-include-articles-collection.json
