#%RAML 1.0
title: ami
baseUri: https://pacific-peak-31437.herokuapp.com/api/
version: v1
mediaType: [ application/json ]
protocols: [ HTTPS ]

uses:
  library: ami-library-auth.raml

/auth:
  description: "Методы авторизации"
  /register:
    post:
      description: "Регистрация нового пользователя"
      body:
        application/x-www-form-urlencoded:
          type: library.Register
      responses:
        200:
          body:
            application/json:
              properties:
                user:
                  type: object
                  required: true
                accessToken:
                  type: string
                  required: true
              example: !include ami-include-auth-data.json
  /login:
    post:
      description: "Авторизация пользователя"
      body:
        application/x-www-form-urlencoded:
          properties:
            email:
              required: true
              type: string
            password:
              description: "Хэш пароля алгоритма MD5"
              required: true
              type: string
      responses:
        200:
          body:
            application/json:
              properties:
                user:
                  type: object
                  required: true
                accessToken:
                  type: string
                  required: true
              example: !include ami-include-auth-data.json

  /restore:
    post:
      description: "Восстановление пароля пользователя"
      body:
        application/x-www-form-urlencoded:
          properties:
            email:
              required: true
              type: string
      responses:
        200:
          body:
            application/json:
              properties:
                message:
                  type: string
                  required: true
              example: !include ami-include-auth-restore-success.json
/token:
  /refresh:
    post:
      description: "Обновление времени действия токена доступа"
      body:
        application/x-www-form-urlencoded:
          properties:
            accessToken:
              required: true
              type: string
      responses:
        200:
          body:
            application/json:
              properties:
                accessToken: string
              example: !include ami-include-token-refresh-success.json
/users:
  description: "Коллекция пользователей ami"
  /{userId}:
    description: "Модель пользователя"
    get:
      description: "Получение подробной информации о пользователе"
      headers:
        AccessToken: string
      responses:
        200:
          body:
            application/json:
              properties:
                userId: string
                email: string
                name: string
                surname: string
                birthdate: number
              example: !include ami-include-users-single.json
        404:
          body:
            application/json:
              properties:
                message: string
              example: |
                {
                  "message": "Пользователь не найден"
                }
    put:
      description: "Обновление данных пользователя"
/history:
  /water:
    get:
      description: "Получение истории выпитой воды"
      headers:
        AccessToken: string
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                amount: number
                drinkedAt: number
              example: !include ami-include-history-water-collection.json
    post:
      description: "Добавление информации о выпитой воде"
      headers:
        AccessToken: string
      body:
        application/x-www-form-urlencoded:
          properties:
            amount:
              required: true
              type: number
            drinkedAt:
              required: true
              type: number
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                amount: number
                drinkedAt: number
              example: !include ami-include-history-water-item.json
    delete:

  /weight:
    get:
      description: "Получение истории взвешиваний"
      headers:
        AccessToken: string
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                amount: number
                drinkedAt: number
              example: !include ami-include-history-weight-collection.json
    post:
      description: "Добавление информации о новом взвешивании"
      headers:
        AccessToken: string
      body:
        application/x-www-form-urlencoded:
          properties:
            amount:
              required: true
              type: number
            weighedAt:
              required: true
              type: number
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                amount: number
                weighedAt: number
              example: !include ami-include-history-weight-item.json
    delete:

  /sleep:
    get:
      description: "Получение истории сна"
      headers:
        AccessToken: string
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                endAt: number
                riseAt: number
              example: !include ami-include-history-sleep-collection.json
    post:
      description: "Добавление информации о прошедшем сне"
      headers:
        AccessToken: string
      body:
        application/x-www-form-urlencoded:
          properties:
            endAt:
              required: true
              type: number
            riseAt:
              required: true
              type: number
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                endAt: number
                riseAt: number
              example: !include ami-include-history-sleep-item.json
    delete:

  /tasks:
    get:
      description: "Получение истории сна"
      headers:
        AccessToken: string
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                title: string
                notifyAt: number
                createdAt: number
              example: !include ami-include-history-task-collection.json
    post:
      description: "Добавление информации о новой задаче"
      headers:
        AccessToken: string
      body:
        application/x-www-form-urlencoded:
          properties:
            title:
              required: true
              type: string
            notifyAt:
              required: false
              type: number
            createdAt:
              required: true
              type: number
      responses:
        200:
          body:
            application/json:
              properties:
                id: string
                title: string
                notifyAt: number
                createdAt: number
              example: !include ami-include-history-task-item.json
    delete:

/articles:
  get:
    description: "Получение списка статей"
    responses:
      200:
        body:
          application/json:
            properties:
              id: string
              title: string
              content: string
              createdAt: number
            example: !include ami-include-articles-collection.json
