#%RAML 1.0 Library
types:

  # Register

  RegisterRequest:
    properties:
      email:
        type: string
        required: true
      password:
        description: Хэш пароля алгоритма MD5
        type: string
        required: true
      name:
        type: string
        required: true
      surname:
        type: string
        required: true
      birthday:
        description: Дата рождения (timestamp)
        type: number
        required: true
      weight:
        description: Последний вес пользователя
        type: number
        required: true
      height:
        description: Рост пользователя
        type: number
        required: true
      appleId:
        description: ID пользователя авторизации через Apple ID
        type: string
        required: false
      vkId:
        description: ID пользователя авторизации через VK
        type: number
        required: false

  RegisterResponse200:
    properties:
      user:
        type: object
        required: true
      accessToken:
        type: string
        required: true
    example: !include ami-include-auth-data.json

  # Login
  LoginRequest:
    properties:
      email:
        required: true
        type: string
      password:
        description: "Хэш пароля алгоритма MD5"
        required: true
        type: string

  LoginResponse200:
    properties:
      user:
        type: object
        required: true
      accessToken:
        type: string
        required: true
    example: !include ami-include-auth-data.json

  # Restore
  RestoreRequest:
    properties:
      email:
        required: true
        type: string

  RestoreResponse200:
    properties:
      message:
        type: string
        required: true
    example: !include ami-include-auth-restore-success.json
