#%RAML 1.0 Library
types:

  # Register

  RegisterOK:
    properties:
      user:
        type: object
        required: true
      accessToken:
        type: string
        required: true
    example: !include ami-include-auth-data.json

  Register400:
    properties:
      message:
        type: string
        required: true
    example: |
      {
        message: "Пользователь с таким Email уже существует"
      }

  # Login

  LoginRequest:
    properties:
      email:
        required: true
        type: string
      password:
        description: "Хэш пароля алгоритма MD5"
        required: true
        type: string

  LoginOK:
    properties:
      user:
        type: object
        required: true
      accessToken:
        type: string
        required: true
    example: !include ami-include-auth-data.json

  Login400:
    properties:
      message:
        type: string
        required: true
    example: |
      {
        message: "Пользователь с таким Email не найден"
      }

  # Restore

  RestoreRequest:
    properties:
      email:
        required: true
        type: string

  RestoreOK:
    properties:
      message:
        type: string
        required: true
    example: !include ami-include-auth-restore-success.json
